# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pacote Exkyn Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PASTA: ${{ github.workspace }}\"OUTPUT"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restaura as Dependencias
      run: dotnet restore
      
    - name: Gera o Pacote
      run: dotnet build -c Release -o out

    - name: Publica Pacote no Github
      run: dotnet nuget add source --username dmodesigner --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github ${{ secrets.NUGET_PACKAGE_GITHUB }}
        
    - name: Publica Pacote no Nuget
      run: dotnet nuget push ${{ env.PASTA }}\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
